#### Instalar Statsbombpy

In [1]:
pip install statsbombpy

Requirement already satisfied: statsbombpy in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (1.1.1)
Requirement already satisfied: pandas in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from statsbombpy) (1.4.0)
Requirement already satisfied: nose2 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from statsbombpy) (0.10.0)
Requirement already satisfied: inflect in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from statsbombpy) (5.3.0)
Requirement already satisfied: requests in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from statsbombpy) (2.27.1)
Requirement already satisfied: joblib in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from statsbombpy) (1.1.0)
Requirement already satisfied: requests-cache in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from statsbombpy) (0.8.1)
Requirement already satisfied: six>=1.7 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from nose2->statsbombpy) (1.16.0)
Requirement already satisfied: coverage>=4.4.1 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from nose2->statsbombpy) (5.5)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from pandas->statsbombpy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from pandas->statsbombpy) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from pandas->statsbombpy) (1.22.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests->statsbombpy) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests->statsbombpy) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests->statsbombpy) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests->statsbombpy) (1.26.8)
Requirement already satisfied: attrs<22.0,>=21.2 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests-cache->statsbombpy) (21.4.0)
Requirement already satisfied: cattrs<2.0,>=1.8 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests-cache->statsbombpy) (1.8.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests-cache->statsbombpy) (1.4.4)
Requirement already satisfied: url-normalize<2.0,>=1.4 in /Users/enzovillafuerte/opt/anaconda3/lib/python3.8/site-packages (from requests-cache->statsbombpy) (1.4.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from statsbombpy import sb

#### Data de competiciones

In [3]:
sb.competitions()

credentials were not supplied. open data access only

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,16,4,Europe,Champions League,male,False,False,2018/2019,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-07-09T14:06:05.802
1,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
2,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
3,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,26,Europe,Champions League,male,False,False,2014/2015,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
5,16,25,Europe,Champions League,male,False,False,2013/2014,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
6,16,24,Europe,Champions League,male,False,False,2012/2013,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-07-10T13:41:45.751
7,16,23,Europe,Champions League,male,False,False,2011/2012,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
8,16,22,Europe,Champions League,male,False,False,2010/2011,2022-01-26T21:07:11.033473,2021-06-13T16:17:31.694,None,2022-01-26T21:07:11.033473
9,16,21,Europe,Champions League,male,False,False,2009/2010,None,None,None,None
10,16,41,Europe,Champions League,male,False,False,2008/2009,2021-11-07T14:20:01.699993,2021-06-13T16:17:31.694,None,2021-11-07T14:20:01.699993
11,16,39,Europe,Champions League,male,False,False,2006/2007,2021-03-31T04:18:30.437060,2021-06-13T16:17:31.694,None,2021-03-31T04:18:30.437060
12,16,37,Europe,Champions League,male,False,False,2004/2005,2021-04-01T06:18:57.459032,2021-06-13T16:17:31.694,None,2021-04-01T06:18:57.459032
13,16,44,Europe,Champions League,male,False,False,2003/2004,2021-04-01T00:34:59.472485,2021-06-13T16:17:31.694,None,2021-04-01T00:34:59.472485
14,16,76,Europe,Champions League,male,False,False,1999/2000,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
15,37,90,England,FA Women's Super League,female,False,False,2020/2021,2021-07-01T18:14:40.756,2021-06-13T16:17:31.694,None,2021-07-01T18:14:40.756
16,37,42,England,FA Women's Super League,female,False,False,2019/2020,2021-06-01T13:01:18.188,2021-06-13T16:17:31.694,None,2021-06-01T13:01:18.188
17,37,4,England,FA Women's Super League,female,False,False,2018/2019,2021-12-02T12:09:35.585046,2021-06-13T16:17:31.694,None,2021-12-02T12:09:35.585046
18,43,3,International,FIFA World Cup,male,False,True,2018,2021-12-06T23:11:59.985953,2021-06-13T16:17:31.694,None,2021-12-06T23:11:59.985953
19,11,90,Spain,La Liga,male,False,False,2020/2021,2022-01-07T18:10:56.809473,2021-10-30T04:19:36.116600,2021-09-17T15:18:33.787790,2022-01-07T18:10:56.809473
20,11,42,Spain,La Liga,male,False,False,2019/2020,2021-06-15T15:35:02.673,2021-06-13T16:17:31.694,None,2021-06-15T15:35:02.673
21,11,4,Spain,La Liga,male,False,False,2018/2019,2021-11-02T17:53:14.529952,2021-07-09T14:53:22.103024,None,2021-11-02T17:53:14.529952
22,11,1,Spain,La Liga,male,False,False,2017/2018,2022-02-01T23:05:45.445067,2021-06-13T16:17:31.694,None,2022-02-01T23:05:45.445067
23,11,2,Spain,La Liga,male,False,False,2016/2017,2022-01-25T22:51:59.353598,2021-06-13T16:17:31.694,None,2022-01-25T22:51:59.353598
24,11,27,Spain,La Liga,male,False,False,2015/2016,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
25,11,26,Spain,La Liga,male,False,False,2014/2015,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
26,11,25,Spain,La Liga,male,False,False,2013/2014,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
27,11,24,Spain,La Liga,male,False,False,2012/2013,2021-10-27T15:44:43.940862,2021-06-13T16:17:31.694,None,2021-10-27T15:44:43.940862
28,11,23,Spain,La Liga,male,False,False,2011/2012,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
29,11,22,Spain,La Liga,male,False,False,2010/2011,2021-11-11T22:57:42.361902,2021-06-13T16:17:31.694,None,2021-11-11T22:57:42.361902
30,11,21,Spain,La Liga,male,False,False,2009/2010,2021-10-26T13:56:40.989214,2021-06-13T16:17:31.694,None,2021-10-26T13:56:40.989214
31,11,41,Spain,La Liga,male,False,False,2008/2009,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
32,11,40,Spain,La Liga,male,False,False,2007/2008,2021-10-26T13:13:56.180589,2021-06-13T16:17:31.694,None,2021-10-26T13:13:56.180589
33,11,39,Spain,La Liga,male,False,False,2006/2007,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
34,11,38,Spain,La Liga,male,False,False,2005/2006,2021-11-28T23:00:27.747396,2021-06-13T16:17:31.694,None,2021-11-28T23:00:27.747396
35,11,37,Spain,La Liga,male,False,False,2004/2005,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
36,49,3,United States of America,NWSL,female,False,False,2018,2021-11-06T05:53:29.435016,2021-06-13T16:17:31.694,None,2021-11-06T05:53:29.435016
37,2,44,England,Premier League,male,False,False,2003/2004,2021-11-14T22:29:00.646120,2021-06-13T16:17:31.694,None,2021-11-14T22:29:00.646120
38,55,43,Europe,UEFA Euro,male,False,True,2020,2022-02-01T17:20:34.319496,2021-11-11T13:54:37.507376,2021-11-11T13:54:37.507376,2022-02-01T17:20:34.319496
39,72,30,International,Women's World Cup,female,False,True,2019,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00

#### Ver los partidos del World Cup 2018

In [5]:
df = sb.matches(competition_id=43, season_id=3)
df[df.home_team=="Peru"]

credentials were not supplied. open data access only

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_stage,stadium,referee,data_version,shot_fidelity_version,xy_fidelity_version
37,7532,2018-06-16,18:00:00.000,International - FIFA World Cup,2018,Peru,Denmark,0,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,1,Group Stage,Mordovia Arena (Saransk),Bakary Papa Gassama,1.0.2,None,None

### Lineups

In [7]:
sb.lineups(match_id=7532)["Peru"]

credentials were not supplied. open data access only

,player_id,player_name,player_nickname,jersey_number,country,cards,positions
0,3632,André Martín Carrillo Díaz,André Carrillo,18,Peru,[],"[{'position_id': 17, 'position': 'Right Wing',..."
1,5518,Miguel Ángel Trauco Saavedra,Miguel Trauco,6,Peru,[],"[{'position_id': 6, 'position': 'Left Back', '..."
2,5519,Christian Alberto Cueva Bravo,Christian Cueva,8,Peru,[],"[{'position_id': 19, 'position': 'Center Attac..."
3,5521,Luis Jan Piers Advíncula Castrillón,Luis Advíncula,17,Peru,[],"[{'position_id': 2, 'position': 'Right Back', ..."
4,5523,Renato Fabrizio Tapia Cortijo,Renato Tapia,13,Peru,"[{'time': '37:18', 'card_type': 'Yellow Card',...","[{'position_id': 13, 'position': 'Right Center..."
5,5525,Édison Michael Flores Peralta,Edison Flores,20,Peru,[],"[{'position_id': 21, 'position': 'Left Wing', ..."
6,5526,Pedro Jesús Aquino Sánchez,Pedro Aquino,23,Peru,[],"[{'position_id': 13, 'position': 'Right Center..."
7,5528,Pedro David Gallese Quiróz,Pedro Gallese,1,Peru,[],"[{'position_id': 1, 'position': 'Goalkeeper', ..."
8,5529,Víctor Yoshimar Yotún Flores,Yoshimar Yotún,19,Peru,[],"[{'position_id': 15, 'position': 'Left Center ..."
9,5530,Christian Guillermo Martín Ramos Garagay,Christian Ramos,15,Peru,[],"[{'position_id': 3, 'position': 'Right Center ..."
10,5531,Jefferson Agustín Farfán Guadalupe,Jefferson Farfán,10,Peru,[],"[{'position_id': 23, 'position': 'Center Forwa..."
11,5532,Alberto Junior Rodríguez Valdelomar,Alberto Rodríguez,2,Peru,[],"[{'position_id': 5, 'position': 'Left Center B..."
12,5533,Raúl Mario Ruidíaz Misitich,Raúl Ruidíaz,11,Peru,[],"[{'position_id': 23, 'position': 'Center Forwa..."
13,5535,José Paolo Guerrero Gonzáles,Paolo Guerrero,9,Peru,[],"[{'position_id': 21, 'position': 'Left Wing', ..."
14,5738,Anderson Santamaría Bardales,Anderson Santamaría,4,Peru,[],[]
15,6313,Wilder José Cartagena Mendoza,Wilder Cartagena,16,Peru,[],[]
16,6315,Christopher Paolo César Hurtado Huertas,Paolo Hurtado,7,Peru,[],[]
17,13435,Andy Jorman Polo Andrade,Andy Polo,14,Peru,[],[]
18,33176,Miguel Gianpierre Araujo Blanco,Miguel Araujo,5,Peru,[],[]
19,35004,José Aurelio Carvallo Alonso,José Carvallo,21,Peru,[],[]
20,35009,Aldo Sebastián Corzo Chávez,Aldo Corzo,3,Peru,[],[]
21,35017,Carlos Alberto Cáceda Oyaguez,None,12,Peru,[],[]
22,35195,Nilson Evair Loyola Morales,Nilson Loyola,22,Peru,[],[]

In [8]:
events = sb.events(match_id=7532)

credentials were not supplied. open data access only

In [9]:
events.columns

Index(['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure',
       'block_deflection', 'carry_end_location', 'clearance_aerial_won',
       'counterpress', 'dribble_nutmeg', 'dribble_outcome', 'dribble_overrun',
       'duel_outcome', 'duel_type', 'duration', 'foul_committed_advantage',
       'foul_committed_card', 'foul_committed_offensive',
       'foul_committed_penalty', 'foul_committed_type', 'foul_won_advantage',
       'foul_won_defensive', 'foul_won_penalty', 'goalkeeper_body_part',
       'goalkeeper_end_location', 'goalkeeper_outcome', 'goalkeeper_position',
       'goalkeeper_technique', 'goalkeeper_type', 'id', 'index',
       'interception_outcome', 'location', 'match_id', 'minute',
       'pass_aerial_won', 'pass_angle', 'pass_assisted_shot_id',
       'pass_backheel', 'pass_body_part', 'pass_cross', 'pass_cut_back',
       'pass_deflected', 'pass_end_location', 'pass_goal_assist',
       'pass_height', 'pass_length', 'pass_miscommunication', 'pass_outcome',
       'pass_recipient', 'pass_shot_assist', 'pass_switch', 'pass_type',
       'period', 'play_pattern', 'player', 'position', 'possession',
       'possession_team', 'related_events', 'second', 'shot_aerial_won',
       'shot_body_part', 'shot_end_location', 'shot_first_time',
       'shot_freeze_frame', 'shot_key_pass_id', 'shot_one_on_one',
       'shot_outcome', 'shot_statsbomb_xg', 'shot_technique', 'shot_type',
       'substitution_outcome', 'substitution_replacement', 'tactics', 'team',
       'timestamp', 'type', 'under_pressure'],
      dtype='object')

In [11]:
events[events.shot_statsbomb_xg.isnull()==False]

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,counterpress,dribble_nutmeg,dribble_outcome,dribble_overrun,...,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,timestamp,type,under_pressure
2992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.010185,Half Volley,Open Play,NaN,NaN,NaN,Peru,00:04:52.880,Shot,True
2993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.009402,Normal,Open Play,NaN,NaN,NaN,Peru,00:07:11.200,Shot,NaN
2994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.016311,Normal,Open Play,NaN,NaN,NaN,Peru,00:10:49.880,Shot,True
2995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.024569,Normal,Open Play,NaN,NaN,NaN,Peru,00:12:06.040,Shot,True
2996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.011180,Normal,Open Play,NaN,NaN,NaN,Peru,00:13:35.120,Shot,NaN
2997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.014436,Normal,Open Play,NaN,NaN,NaN,Peru,00:14:11.080,Shot,True
2998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.038267,Normal,Open Play,NaN,NaN,NaN,Denmark,00:19:37.360,Shot,NaN
2999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.019103,Normal,Open Play,NaN,NaN,NaN,Denmark,00:26:22.293,Shot,True
3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.103541,Normal,Open Play,NaN,NaN,NaN,Peru,00:28:21.733,Shot,NaN
3001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.087013,Normal,Free Kick,NaN,NaN,NaN,Denmark,00:38:46.520,Shot,NaN
3002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.016224,Half Volley,Open Play,NaN,NaN,NaN,Denmark,00:38:48.573,Shot,NaN
3003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.028146,Half Volley,Open Play,NaN,NaN,NaN,Denmark,00:40:45.000,Shot,NaN
3004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.760000,Normal,Penalty,NaN,NaN,NaN,Peru,00:45:42.240,Shot,NaN
3005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.091307,Normal,Open Play,NaN,NaN,NaN,Denmark,00:46:59.120,Shot,True
3006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.015113,Normal,Open Play,NaN,NaN,NaN,Peru,00:04:55.640,Shot,NaN
3007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.008608,Normal,Open Play,NaN,NaN,NaN,Denmark,00:05:28.453,Shot,True
3008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.011762,Half Volley,Open Play,NaN,NaN,NaN,Denmark,00:07:54.053,Shot,NaN
3009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.193463,Normal,Open Play,NaN,NaN,NaN,Peru,00:11:02.440,Shot,NaN
3010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.200544,Normal,Open Play,NaN,NaN,NaN,Denmark,00:13:32.040,Shot,NaN
3011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.129279,Normal,Open Play,NaN,NaN,NaN,Peru,00:15:07.920,Shot,NaN
3012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.128379,Normal,Open Play,NaN,NaN,NaN,Peru,00:18:37.240,Shot,NaN
3013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.034748,Normal,Open Play,NaN,NaN,NaN,Peru,00:23:19.600,Shot,True
3014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.021467,Normal,Open Play,NaN,NaN,NaN,Peru,00:27:06.080,Shot,NaN
3015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.089640,Backheel,Open Play,NaN,NaN,NaN,Peru,00:33:28.240,Shot,NaN
3016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.135146,Normal,Open Play,NaN,NaN,NaN,Denmark,00:36:45.720,Shot,NaN
3017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.184018,Normal,Open Play,NaN,NaN,NaN,Peru,00:38:20.200,Shot,NaN
3018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.288833,Normal,Open Play,NaN,NaN,NaN,Denmark,00:40:25.640,Shot,NaN
3019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.085115,Normal,Open Play,NaN,NaN,NaN,Peru,00:49:02.240,Shot,True

In [12]:
events.to_csv("Peru_WC18_Den.csv", index=None)

In [13]:
import pandas as pd

In [14]:
df1 = pd.read_csv("Peru_WC18_Den.csv")

In [15]:
df1.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,counterpress,dribble_nutmeg,dribble_outcome,dribble_overrun,...,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Peru,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Denmark,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Denmark,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Peru,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Denmark,00:00:00.000,Half Start,NaN

In [18]:
df1.groupby(by=["team"])[["shot_statsbomb_xg"]].sum()

         shot_statsbomb_xg
team
Denmark           0.924954
Peru              1.830846